/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7833086d-da2e-4f7f-ba37-6d1bce1c4d36",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_PHT3f4iJc",
    "aws_user_pools_web_client_id": "2jkjmnrd5pq8afffh0o581knnp",
    "oauth": {},
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_cognito_login_mechanisms": [
        "EMAIL"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_appsync_graphqlEndpoint": "https://v4deygozfza4jejgfqu7go2t2i.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-koksr446w5ddxmw4njich2dexu"
};


export default awsmobile;
